FROM python:3.9-slim as base

# Setup env
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONFAULTHANDLER 1

FROM base AS python-deps

# Install poetry and compilation dependencies
RUN apt-get update && apt-get install gcc ffmpeg -y --no-install-recommends
RUN pip install --upgrade pip
RUN pip install poetry

# Install python dependencies in /.venv
COPY pyproject.toml .
COPY poetry.lock .
RUN poetry config virtualenvs.in-project true
RUN poetry install

FROM base AS runtime

# Copy virtual env from python-deps stage
COPY --from=python-deps /.venv /.venv
ENV PATH="/.venv/bin:$PATH"

# Create and switch to a new user
RUN useradd --create-home radio
WORKDIR /home/radio
USER radio

# Install application into container
COPY .env .
COPY radio .

# Run the application
ARG CHANNEL
ENV OUTPUT_DIR=$CHANNEL
ARG M3U8_URL
ENV M3U8_URL=$M3U8_URL
ARG ALERT
ENV ALERT=$ALERT

RUN mkdir ${CHANNEL}
ENTRYPOINT ["python", "-m", "fetch_hls_stream"]
