version: '3.9'

services:
  master:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 9333:9333
      - 19333:19333
      - 9324:9324
    command: master -mdir=/data -ip=master -ip.bind=0.0.0.0 -metricsPort=9324 -volumeSizeLimitMB=1000
    volumes:
      - /var/seaweedfs/master:/data
    restart: always
  volume:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 8080:8080
      - 18080:18080
      - 9328:9328
    command: volume -dir=/data -mserver="master:9333" -ip.bind=0.0.0.0 -port=8080 -metricsPort=9328 -max=350
    depends_on:
      - master
    volumes:
      - /var/seaweedfs/volume:/data
    restart: always
  filer:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 8888:8888
      - 18888:18888
      - 9326:9326
    command: filer -master="master:9333" -ip.bind=0.0.0.0 -metricsPort=9326
    tty: true
    stdin_open: true
    depends_on:
      - master
      - volume
    restart: always
  s3:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 8333:8333
      - 9327:9327
    command: s3 -config=/etc/seaweedfs/s3.json -filer="filer:8888" -ip.bind=0.0.0.0 -metricsPort=9327
    depends_on:
      - master
      - volume

      - filer
    volumes:
      - /etc/seaweedfs/s3.json:/etc/seaweedfs/s3.json:ro
    restart: always
  webdav:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 7333:7333
    command: 'webdav -filer="filer:8888"'
    depends_on:
      - master
      - volume
      - filer
    restart: always
  prometheus:
    image: prom/prometheus:v2.21.0
    ports:
      - 9000:9090
    volumes:
      - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - s3
    restart: always

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16
          gateway: 10.10.0.1
